
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barrage?characterEncoding=utf8
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: -1
    sentinel:
      master: barrage
      nodes:
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#          hibernate:
#            format_sql: true
#            show_sql: true
server:
  port: 80
logging:
  path: /java/log
  level: info
