
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barrage?characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 80
logging:
  path: /java/log
  level: warn
